export const FETCH_DIRECTORY = 'FETCH_DIRECTORY';
export const SEARCH_DIRECTORY = 'SEARCH_DIRECTORY';
export const DELETE_DIRECTORY_ITEM = 'DELETE_DIRECTORY_ITEM';
export const RENAME_DIRECTORY_ITEM = 'RENAME_DIRECTOY_ITEM';
